### ISSUE TITLE
LINK : fatal error LNK1181: cannot open input file 'Win32-Debug\picture-x86-asm-sad.obj'

### ISSUE THREAD

**Issue by sdancer75** [ultravideo/kvazaar#189]
I get the link error " LINK : fatal error LNK1181: cannot open input file 'Win32-Debug\picture-x86-asm-sad.obj'".

Under "kvazaar-1.2.0\build\kvazaar_lib\Win32-Debug" there is no picture-x86-asm-sad.asm file to compile. 

What seems to be wrong here ?

**Comment by Arizer** [comment]
Hi,

Are you missing vsyasm.exe in %PATH%? It is required as stated in readme under "Visual Studio".

The asm file should exist in kvazaar\src\strategies\x86_asm\ by the way.

**Comment by sdancer75** [comment]
Hi, thanks for your answer. No vsyasm.exe is already in the path.

The problem solved under VS2017 with this : 

**Kvazaar_lib properties --> YASM assembler --> Include paths**  

and I added the **$(SolutionDir)..\src\strategies\x86_asm;**

Now compiler is created successfully the _kvazaar_lib.lib_ :-)

**Comment by Arizer** [comment]
Thanks!

Funnily enough, I just heard this issue exists with VS2017 when someone in our group was compiling Kvazaar for the first time. Many of us still use older versions of Visual Studio.

Let's keep this open until we fix the issue.

**Comment by Arizer** [comment]
Should be working now (6be8195). Seems to compile all the .asm files after any change, though.

**Comment by sdancer75** [comment]
Hey thanks,

BTW, Kvazaar implements wavefront encoding the same way as HM (hevc test software) impement it ?

**Comment by Arizer** [comment]
Not sure if I understood the question 100%.

Kvazaar implements wavefront parallel processing (--wpp option, enabled by default). Standard HEVC bitstream is produced. With default settings, if multiple cores and threads are available, Kvazaar encodes multiple CTU rows on multiple frames concurrently.

If this doesn't answer to your question, could you be more specific?

**Comment by Arizer** [comment]
Unfortunately there is not a file or anything you can just copy and paste to HM. Kvazaar is made from scratch, which means practically all the data structures and other important stuff are different at least on some level. But as I said, the bitstreams conform to the HEVC standard.

Educational usage should be ok nevertheless. Since you mentioned that, you might want to look into the visualizer: https://github.com/ultravideo/kvazaar#visualization-windows-only It shows pretty nicely how for example WPP works.

(If there is still more you need to know, it would be good to have a separate issue for this or you could drop by our IRC channel)
