### ISSUE TITLE
Problems about ROI encryption

### ISSUE THREAD

**Issue by YanjunHH** [ultravideo/kvazaar#217]
Hi, i try to use kvazaar encode the video based on the ROI. This id the input roi.txt format.
![image](https://user-images.githubusercontent.com/37657848/49064572-45629d00-f256-11e8-8f09-2ac562a33ae1.png)
When I play the video while coding, the effect is as follows.
![image](https://user-images.githubusercontent.com/37657848/49064776-f832fb00-f256-11e8-834e-ddb8751833c1.png)
But I want to completely cover the face like this
![image](https://user-images.githubusercontent.com/37657848/49065117-033a5b00-f258-11e8-8831-cab9de9d2eb3.png)
what should i do ? Looking forward to your reply.

**Comment by fador** [comment]
Hi,

The encryption is a separate process, ROI is only used for changing the quality of regions.

Typically the encryption is done like this:
kvazaar -i input.yuv --preset=ultrafast --input-res=3840x2160 --tiles=4x4 --crypto=intra_pred_modes+mvs+mv_signs+trans_coeffs+trans_coeff_signs --mv-constraint=frametilemargin -o out.hevc

Which will encrypt the video in tiles and use a motion vector constraint over the tiles.

We have used GPAC/OpenHEVC to decrypt some tiles and leave other tiles encrypted (via GUI selection) to get this partially encrypted look in some demos.

At the moment we don't have an option to only encrypt some tiles in Kvazaar, we might add the option at some point since it has been used in our internal testing. It should not be too hard to modify the encryption process to support this kind of selective encryption..

**Comment by fador** [comment]
Great!

If you want to add some files to the compilation, please edit `src/Makefile.am` where the list of sources is located.
Then you should be able to compile Kvazaar:
```
./autogen.sh
./configure
make
```

**Comment by tantao0675** [comment]
@YanjunHH  Hi, I'm researching HEVC encode recently, But I am confused about the parameter settings of the kvazaar encoder. can you provide used kvazaar command (including parameters), thank you every much.

**Comment by YanjunHH** [comment]
@fador hi fador
Now I need to add a .so for kvazaar encoder.  How should I edit `src/Makefile. am`？
Looking forward to your reply!

**Comment by fador** [comment]
@YanjunHH I believe easiest way would be to edit `configure.ac` and add -lyourlib to LIBS
`LIBS="-lyourlib $LIBS"`
For setting the path you can `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/your/lib/path/`
