### ISSUE TITLE
error while using the encoding commands

### ISSUE THREAD

**Issue by spaul13** [ultravideo/kvazaar#223]
Hi,
I installed and build the x265 encoder successfully on ubuntu platform. 
Now, I am trying to encode an image using the following command 

kvazaar -i test.png --input-res 4096*2048 -o output.mp4
kvazaar --input test.png --output output.mp4.

But nothing is working. Showing the Kvazaar usage pattern only. 
Can anyone please tell me what is wrong with the command and how to encode a png file into .mp4 file?

**Comment by Arizer** [comment]
Hi,

There seems to be some confusion here:

1) Kvazaar and x265 are different projects. Both of them are HEVC encoders, though.
2) The format for input resolution includes "x" instead of "*" as stated in the readme.
3) Kvazaar does not accept .png files as input. Only yuv is supported at the moment.
4) Kvazaar does not output .mp4 files but raw HEVC bitstreams. Those bitstreams can be put into mp4 container with other tools.

So outside Kvazaar, you'd need to convert png to yuv before encoding. After encoding you can insert the output file into a mp4 container if you really need to.

You might want to have a look at FFmpeg. It is able to make many kinds of file type conversions.
