### ISSUE TITLE
MinGW Compile Error

### ISSUE THREAD

**Issue by HikariS97** [ultravideo/kvazaar#263]
As below
I'm not familiar with MinGW Complier, could someone give me some advices?
![微信截图_20200423111201](https://user-images.githubusercontent.com/48763518/80055051-5438a680-8553-11ea-86ae-5af9feb07fad.png)

**Comment by fador** [comment]
Hi,

The problem seems to be because of an old version of automake, 1.11.1 or earlier. MinGW doesn't seem to provide any later one (this one is from 2009).
I would recommend using Mingw-w64/Msys2, which supports more up-to-date compiling tools.

However, you can fix the problem by running the following in the Kvazaar folder:
`sed -i.orig -e "s/AM_PROG_AR/m4_ifdef([AM_PROG_AR], [AM_PROG_AR])/" configure.ac`
I had to also manually select `mingw32-pthreads-w32-dev` package because configure was complaining about missing POSIX threads.

Hopefully this helps!

**Comment by fador** [comment]
I forgot to mention that with the Mingw + gcc we actually disable AVX2 optimizations, so Kvazaar will be slow compared to other builds.

This also one reason to use msys2, so you could install clang, and use that to compile kvazaar with AVX2 optimizations:
`CC=clang ./configure --disable-shared`

**Comment by HikariS97** [comment]
@fador Thx ! It goes well by using MinGW64 + MSYS2. Thanks for your help. Closing this issure
