### ISSUE TITLE
--sao off is not recognized

### ISSUE THREAD

**Issue by Ichunjo** [ultravideo/kvazaar#283]
Hello, I'm using the master branch and did some tests but:
`Input error: Extra argument found: "off"`

Command used: `kvazaar.exe -i in.mkv --input-res 1920x1080 -o out.hevc --input-bitdepth 10 --sao off`

It's working when passing `--no-sao` although the command is not documented.

**Comment by Jovasa** [comment]
Because the `--sao` has an optional argument the argument has to be passed with "=", for example `--sao=off`. `--sao` would be equivalent to `--sao=full` and `--no-sao` to `--sao=off`. However since this is pretty much the only parameter with functionality I've removed it in da09d498908f123b164ec30b910e016197474446. After that commit `--sao` doesn't work anymore but `--sao off` will work as expected.
