### ISSUE TITLE
How to execute Cryptoo.cpp code over sample .hevc file in Kvazaar? 

### ISSUE THREAD

**Issue by Abhijeet241093** [ultravideo/kvazaar#285]
How to execute crypto.cpp code over the sample file?

Basically I just want to encrypt DC coefficent in I frame and motion vector in P and B frame. Is it possible then how?

**Comment by Abhijeet241093** [comment]
Hello Sir,

Is anyone kindly answer this question?

**Comment by fador** [comment]
Hi,

It is not possible to select only DC coefficients to encrypt, `trans_coeffs` would encrypt the transform coefficients fully.
To be able to encrypt only DC coeffs, modification would be needed in both Kvazaar and OpenHEVC.
Motion vectors can be encrypted with `--crypto mvs+mv_signs` and would only affect P/B frames, as you have done in #289

Closing this issue since it seems like a duplicate
