### ISSUE TITLE
Cannot set CU Dimensions                    

### ISSUE THREAD

**Issue by saeedranjbar12** [ultravideo/kvazaar#295]
Hi. In the HM cfg files it is possible to set MaxCUWidth and MaxCUHeight but I could not find a similar feature in the current parameters of Kvazaar encoder. I can see that tile sizes can be set but tiles are not the same CUs. Are there any ways to set max dimensions for CU in Kvazaar?

**Comment by Arizer** [comment]
Hi,

For CUs, --pu-depth-intra and --pu-depth-inter options specify the block sizes that are evaluated with the regular method but Kvazaar will still use larger CUs for intra if a good block is found with a fast method (disabling this behavior requires removal of some code).

**Comment by saeedranjbar12** [comment]
Thanks for your response. 
What you mentioned is right for compressing the natural content. However, recently HEVC has been used for compression of tiled deep features (as in [1] and similar papers). The channels in the tiled deep features are smaller than 64x64. So, that would be nice if CTU can be set to the size of each channel (which is smaller in general). 
[1]: DEEP FEATURE COMPRESSION FOR COLLABORATIVE OBJECT DETECTION - https://arxiv.org/pdf/1802.03931.pdf

**Comment by Arizer** [comment]
Thank you for linking the paper.

This comes a bit late but we had some discussion about this use case. The signaling overhead of always splitting large CTUs to 16x16 or smaller CUs is probably not very significant if there are enough feature channels since HEVC is good at adapting to this kind of things. So, just limiting the maximum PU sizes might work pretty well for this. In case you are interested in trying something, you'd need to remove the following part of the code to prevent larger intra CUs from being coded regardless of the command-line parameters:

https://github.com/ultravideo/kvazaar/blob/17c9fc5cc98be44f72f1b6e5be85f5c9572bb603/src/search.c#L740-L782
