### ISSUE TITLE
How to decrypt encrypted video?

### ISSUE THREAD

**Issue by jinyong-yu** [ultravideo/kvazaar#318]
I have two questions.

Once, I did the video encryption through the crypto option of kvazaar. But I don't know how to decrypt it. 

Second, I want to identify the absolute coordinates of the quantized block(or luma block, cb,cr block). Is there a way?

I would be very glad if you could reply to this.
thank you

**Comment by Jovasa** [comment]
Sorry for the long wait.

The decryption can be done using openHEVC specifically the hevc_encryption branch. Unfortunately it has been several years since I have last time used this myself so I cannot provide exact instructions for the decryption.

For the quantized block at what point / where do you need to get the coordinates of the block?

**Comment by jinyong-yu** [comment]
Thank you for answer. Your comment was really helpful.

Anyway, the second question is, I want to apply the crypto feature "KVZ_CRYPTO_TRANSF_COEFF_SIGNS" only to some coding units, can you recommend a way to do this?

**Comment by Jovasa** [comment]
The `kvz_encode_coeff_nxn` function is called from https://github.com/ultravideo/kvazaar/blob/96b00ff5287e95e2a15055e0e8221fc856c18f89/src/encode_coding_tree.c#L117 which happens to have the coordinates of the current TU, so you can edit the function signature of `kvz_encode_coeff_nxn` to include the x and y coordinates. 

However since that function is avx2 optimized you have to do the changes here https://github.com/ultravideo/kvazaar/blob/96b00ff5287e95e2a15055e0e8221fc856c18f89/src/strategies/strategies-encode.h#L49 here https://github.com/ultravideo/kvazaar/blob/96b00ff5287e95e2a15055e0e8221fc856c18f89/src/strategies/generic/encode_coding_tree-generic.h#L44 here https://github.com/ultravideo/kvazaar/blob/96b00ff5287e95e2a15055e0e8221fc856c18f89/src/strategies/generic/encode_coding_tree-generic.c#L40 here https://github.com/ultravideo/kvazaar/blob/96b00ff5287e95e2a15055e0e8221fc856c18f89/src/strategies/avx2/encode_coding_tree-avx2.h#L44 and here https://github.com/ultravideo/kvazaar/blob/96b00ff5287e95e2a15055e0e8221fc856c18f89/src/strategies/avx2/encode_coding_tree-avx2.c#L249

And then you can add the check for correct TU inside the generic and avx2 implementation. Please note that the `kvz_encode_coeff_nxn` is also called from https://github.com/ultravideo/kvazaar/blob/96b00ff5287e95e2a15055e0e8221fc856c18f89/src/rdo.c#L266 but it won't touch the encryption in any way, however you still need to give some dummy data for the coordinates, `0,0` should work fine.

**Comment by jinyong-yu** [comment]
wow.. thank you for your detailed explanation. i think i can solve it!! thank you
