### ISSUE TITLE
Issue with installing Kvazaar on windows 64

### ISSUE THREAD

**Issue by Faiz786-Hp-rgb** [ultravideo/kvazaar#324]
Hello, I am having trouble installing Kvazaar on Windows. I have extracted the zip file in my system 32 folder. And I'm trying to follow the instructions given in the readme file...
```
./autogen.sh
./configure
make
sudo make install
```
But It's not really working. Can someone guide me through the process of installing kvazaar library?

**Comment by fador** [comment]
Hi!

Those instructions are for Linux (and similar) systems, for Windows you would have to use Visual Studio to build Kvazaar.

Could you tell how you are planning to use Kvazaar?

The usual way is to just use the command line interface binary (.exe for windows available in [releases](https://github.com/ultravideo/kvazaar/releases/download/v2.1.0/Kvazaar-2.1.0-win64-release.zip) ) or as a library linked in ffmpeg, but you would have to compile ffmpeg together with Kvazaar in order to use that.

Other than that, the Kvazaar library by itself might not be that useful..

**Comment by Faiz786-Hp-rgb** [comment]
I tried to follow the instruction fro running it on the windows but i am getting this error

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3721	The command "vsyasm.exe -Xvc -f win64 -i "D:\Media-Project\Kvzaar\kvazaar\build\..\src\extras" -i "D:\Media-Project\Kvzaar\kvazaar\build\..\src\extras" -i "D:\Media-Project\Kvzaar\kvazaar\build\..\src\strategies\x86-asm" -d "ARCH_X86_64=1" -d "HAVE_ALIGNED_STACK=1" -o "x64-Release\\" -rnasm -pnasm   "..\..\src\strategies\x86_asm\picture-x86-asm-sad.asm"  "..\..\src\strategies\x86_asm\picture-x86-asm-satd.asm"" exited with code 1.	kvazaar_lib	D:\Media-Project\Kvzaar\kvazaar\build\yasm\vsyasm.targets	46	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file 'D:\Media-Project\Kvzaar\kvazaar\build\x64-Release-libs\kvazaar_lib.lib'	kvazaar_cli	D:\Media-Project\Kvzaar\kvazaar\build\kvazaar_cli\LINK	1	

not creating and kvazaar.exe file  need assistance on this.

**Comment by Faiz786-Hp-rgb** [comment]
installed on ubuntu sucessfully.

**Comment by fador** [comment]
If anyone else has the same problem, the solution is to put `vsyasm.exe` in one of the directories in PATH.
You can see the list from command line with `echo %PATH%`. C:\WINDOWS\system32 is one of those directories.
vsyasm.exe is available at [Yasm website](http://www.tortall.net/projects/yasm/releases/vsyasm-1.3.0-win64.zip) in the separate visual studio zip package.
