### ISSUE TITLE
What kind of low cost FPGA SoCs can be used with kvazaar?

### ISSUE THREAD

**Issue by rajhlinux** [ultravideo/kvazaar#339]
Hello,

I am curious of what kind of low cost FPGA SoCs can be used for kvazaar?

Would like to feed 32 channels of MJPG @1080P 30FPS and transcode to HEVC.

How many FPGAs SoCs would be needed?

Planning to fully custom design such PCB and maybe add PCIe support to get additionally usefulness if connected to a PC. 

Read some papers that Xilinx Spartan-3 FPGAS can do the task:
https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.735.5121&rep=rep1&type=pdf

This paper shows 16x16 TUs requires only 5,000 LUTs using Xilinx Zynq-7000 FPGAs:
https://123dok.com/document/y93297ry-implementasi-hevc-codec-pada-platform-berbasis-fpga-repository.html

From my understanding these FPGAs costs less than $20. 

Thanks.

**Comment by fador** [comment]
Hi!

So I assume you have seen our from some of our papers, that we have used High-Level Synthesis to get Kvazaar running on an FPGA?
In [FPGA-Powered 4K120p HEVC Intra Encoder](https://researchportal.tuni.fi/en/publications/fpga-powered-4k120p-hevc-intra-encoder) paper ([pdf](https://researchportal.tuni.fi/files/20622817/FPGA_Powered_4K120p_HEVC_Intra_2018.pdf)) from 2018 we achieved the 4K120p **Intra-Only** encoding by utilizing both 2.4 GHz dual 14-core Intel Xeon **and** accelerated some of the encoding with **Two** $10k+(?) Arria 10 FPGAs.
This was done using a highly modified version of Kvazaar and Catapult C for the High-Level Synthesis.

This was four years ago, just the Intra part the accelerator was taking around 92 000 ALUTs.

The latest one is [High-Level Synthesis Implementation of an Embedded Real-Time HEVC Intra Encoder on FPGA for Media Applications](https://trepo.tuni.fi/handle/10024/138717) ([pdf](https://trepo.tuni.fi/bitstream/handle/10024/138717/High_Level_Synthesis_Implementation_of_an_Embedded_Real_Time_HEVC_Intra_Encoder_on_FPGA_for_Media_Applications.pdf?sequence=1&isAllowed=y)) from this year. The premise is the same, same hardware but instead of PCIe, the FPGA accelerators were connected over 40 Gigabit Ethernet to achieve the same, with CABAC now in the FPGA side. 

So this version is taking around 90k ALMs + 10k ALM for the CABAC and 12k for connecting things together. (Not sure what is the conversion ratio between ALUT, ALM and LUT btw).

Currently our target is to get real stand-alone version of Kvazaar to FPGA, but still with Intra-only encoding.

I'm sure that some simpler HEVC can be implemented in smaller space, but we have not studied the FPGA implementation from that angle, we just tried make fit Kvazaar there 😅

I'm sorry to say but it does seem really hard to try to fit Kvazaar into one of the cheap boards. And to get that many channels of 1080p 30fps seems unlikely..

In my opinion the best bet would be to use HEVC hardware encoders in GPUs, but I understand that it would be much better to have something open source running on FPGA 😅 I hope you can figure out some way to make things work!

I would also like to add that I'm not the person working with the FPGA encoding in our team, so I might have said something that is not completely accurate.

Best Regards,
Marko

**Comment by rajhlinux** [comment]
Hello Marko, Thank You for your detail answer. I will look into your papers. I'm also interested for standalone HEVC encoding acceleration all taken place in the FPGA.
