### ISSUE TITLE
using other encryption algorithms

### ISSUE THREAD

**Issue by instrol** [ultravideo/kvazaar#340]
kvazaar provides the AES-CFB for encryption. But as far as I know, there are many encryption algorithms for video encryption, such as blowfish, IDEA, RC4, etc. We want to apply these encryption algorithms to kvazaar. What should I do?

**Comment by Jovasa** [comment]
The encryption is currently hardcoded for AES-CFB, which makes changing the encryption algorithm non-trivial task. Basically you'll have to change the key generation in `cabac.c` and change all of the functions suffixed `_encry` to facilitate the new algorithm for updating the `state->crypto_prev_pos`. Unfortunately, I don't think anybody from our current team knows exactly how the `state->crypto_prev_pos` updating works so yuo'll have to figure out it yourself. Of course if you would use OFB opreating mode instead of CFB or a true stream cipher, you wouldn't need to take care of it. (Although if you are interested in security I would obviously advice against true stream ciphers)

**Comment by instrol** [comment]
thank you for your comment. i ll do my best for trying to apply the other encryption algorithms!!!

**Comment by instrol** [comment]
thank you for your comment. i ll do my best for trying to apply the other encryption algorithms!!!
