### ISSUE TITLE
Request: error messages and switching off logging

### ISSUE THREAD

**Issue by farindk** [ultravideo/kvazaar#356]
I have just added a kvazaar encoder plugin to libheif as an alternative HEIC encoder:
https://github.com/strukturag/libheif/commit/2fb10639d8094578c493522f91d7f04e6b7c92ef

I came across two things that I could not find:
- When an API function returns an error, is there any error message or further information that I could pass on?
- Could you add a config parameter to switch off the logging to stdout through the API?

**Comment by Jovasa** [comment]
> When an API function returns an error, is there any error message or further information that I could pass on?

No, not really. Since error handling in general is not easy in C, we do the bare minimum.

> Could you add a config parameter to switch off the logging to stdout through the API?

Kvazaar shouldn't output anything to stdout (except help or version message), so I assume you mean stderr? Even then do you mean error messages from the config parsing, since the actual logging by the encoder is performed by the CLI and not the API version of Kvazaar that you are using. Nevertheless, there is no such option, but if you want to create it yourself we would be happy to accept a pull request for such feature.

**Comment by farindk** [comment]
The following is printed to `stderr` in `api->encoder_open()`:
````
Compiled: INTEL, flags: MMX SSE SSE2
Detected: INTEL, flags: MMX SSE SSE2 SSE3 SSSE3 SSE41 SSE42 AVX AVX2
Available: avx(11) avx2(54) sse2(2) sse41(4) 
In use: avx(1) avx2(54) 
--owf=auto value set to 2.
--threads=auto value set to 8.
````

**Comment by farindk** [comment]
Printing is done here:

https://github.com/ultravideo/kvazaar/blob/37a0404bc8ccdc39515a5aed706205dc53810019/src/strategyselector.c#L538-L591

**Comment by Jovasa** [comment]
Sorry, yes you are correct, this was already brought up in #292 and then answer is pretty much the same still.

**Comment by farindk** [comment]
And all over in this function:
https://github.com/ultravideo/kvazaar/blob/37a0404bc8ccdc39515a5aed706205dc53810019/src/encoder.c#L134
