### ISSUE TITLE
Hello, I would like to ask whether kvazaar supports NVIDIA's GPU-accelerated encoding, and if so, what should I do?

### ISSUE THREAD

**Issue by xuezihao1** [ultravideo/kvazaar#362]
Hello, I would like to ask whether kvazaar supports NVIDIA's GPU-accelerated encoding, and if so, what should I do?

**Comment by fador** [comment]
Hi,

Unfortunately it's not possible to utilize it for Kvazaar, since GPUs implement the full encoder by themself and it's not possible to use just parts of it for our purposes.
Basically you can just use the Nvidia GPU encoder (NVENC) through FFmpeg or other software that supports it, Kvazaar would not be of any help in this.
