### ISSUE TITLE
cmake does not create soversion

### ISSUE THREAD

**Issue by lgbaldoni** [ultravideo/kvazaar#383]
While updating the openSUSE package to 2.3.0, I noticed https://github.com/ultravideo/kvazaar/issues/381, so I tried cmake but the latter won't produce a versioned shared library.

Also, again with cmake, libkvazaar suffers from underlinking, had to add libm (this might be possibly distro-related though).

**Comment by Jovasa** [comment]
Library versioning should be fixed with 621a2bba8f12c9fed07c266e590bc05dea2861b2

The limb check is performed here https://github.com/ultravideo/kvazaar/blob/master/CMakeLists.txt#L225 and apparently it does not work for openSUSE? If you can figure out an openSUSE specific fix for this I'm happy to accept a pull request

**Comment by kmilos** [comment]
Also, the .pc file is now not generated properly w/ autotools...

**Comment by Jovasa** [comment]
>Also, the .pc file is now not generated properly w/ autotools...

Yes, this was already reported in !381 and fixed in f6a9d92a30083b5e228ca1126418e12c515bfa69

**Comment by Jovasa** [comment]
> Thing is, it's the library itself that requires libm:
>
> ```
> --- kvazaar-2.3.0.orig/CMakeLists.txt
> +++ kvazaar-2.3.0/CMakeLists.txt
> @@ -172,7 +172,7 @@ else()
>   endif()
>   set(THREADS_PREFER_PTHREAD_FLAG ON)
>  find_package(Threads REQUIRED)
>-  target_link_libraries(kvazaar PUBLIC Threads::Threads)
>+  target_link_libraries(kvazaar PUBLIC Threads::Threads m)
>```

As long as this fails during CMake configuration if libm is not present this should be fine, because the autotools also fails during configure, if libm is not found. Furthermore, if we are always linking to libm, the check later on should be also removed. 

Otherwise I'm happy with your changes and I'd be happy with a PR.
