### ISSUE TITLE
warning in avx2 code

### ISSUE THREAD

**Issue by vtorri** [ultravideo/kvazaar#401]
I'm compiling on Windows. Here it is:

```
C:/Documents/msys2/home/vincent.torri/gitroot_64/kvazaar/kvazaar-2.3.1/src/strategies/avx2/intra-avx2.c: In function 'kvz_angular_pred_avx2':
C:/Documents/msys2/home/vincent.torri/gitroot_64/kvazaar/kvazaar-2.3.1/src/strategies/avx2/intra-avx2.c:862:26: warning: writing 32 bytes into a r
egion of size 18 [-Wstringop-overflow=]
  862 |       tmp_ref[x + width] = ref_main[x];
      |       ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
C:/Documents/msys2/home/vincent.torri/gitroot_64/kvazaar/kvazaar-2.3.1/src/strategies/avx2/intra-avx2.c:836:11: note: at offset [46, 64] into dest
ination object 'tmp_ref' of size 64
  836 |   uint8_t tmp_ref[2 * 32];
      |           ^~~~~~~
```

**Comment by Jovasa** [comment]
I tried to replicate https://godbolt.org/z/fz1fhW18x but couldn't, though I might be missing something.

Nevertheless, this is false positive on the warning, because if there was an actual buffer overflow I'm pretty sure that our asan or valgrind test would catch it. Additionally, considering that the width can at maximum be 32, that line of code should only touch indexes [31, 63] which is within bounds.

**Comment by Jovasa** [comment]
Also that part of the code was not changed in this release, so the warning should have been present also on earlier releases.

**Comment by vtorri** [comment]
ok, closing
