### ISSUE TITLE
cannot compile library on OSX

### ISSUE THREAD

**Issue by kodabb** [ultravideo/kvazaar#94]
Hi, I am trying to compile kvazaar from git HEAD, but on OSX it yields

```
gcc encmain.o interface_main.o bitstream.o cabac.o checkpoint.o cli.o config.o context.o cu.o encoder.o encoderstate.o rate_control.o filter.o inter.o intra.o kvazaar.o nal.o imagelist.o rdo.o sao.o scalinglist.o search.o strategyselector.o tables.o threadqueue.o transform.o encoder_state-bitstream.o encoder_state-ctors_dtors.o encoder_state-geometry.o image.o videoframe.o yuv_io.o strategies/strategies-picture.o strategies/strategies-nal.o strategies/strategies-dct.o strategies/strategies-ipol.o strategies/generic/nal-generic.o strategies/generic/picture-generic.o strategies/sse2/picture-sse2.o strategies/sse41/picture-sse41.o strategies/altivec/picture-altivec.o strategies/avx2/picture-avx2.o strategies/x86_asm/picture-x86-asm.o strategies/generic/dct-generic.o strategies/avx2/dct-avx2.o strategies/generic/ipol-generic.o strategies/avx2/ipol-avx2.o strategies/x86_asm/picture-x86-asm-sad.o strategies/x86_asm/picture-x86-asm-satd.o -fvisibility=hidden -lm -pthread -m64 -shared -Wl,-soname,libkvazaar.so.0 -o libkvazaar.so.0.0.0
ld: unknown option: -soname
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libkvazaar.so.0.0.0] Error 1
```

`-soname` is unavailable on OSX and it looks like the right extension would be `.dylib`.

**Comment by aryla** [comment]
I tried adding a libkvazaar.dylib target to the Makefile on branch make-dylib. Could you check if it works on your machine?

**Comment by kodabb** [comment]
yep, that worked well for me!
Note however that only a non-versioned library was generated (without even the .0.0.0), so there might be versioning problems in the future.
thanks

**Comment by lu-zero** [comment]
I can revamp the build system set I wrote 1 year ago if you want to go in that direction.

**Comment by nieder** [comment]
* On Darwin, the library file name set by $(DYLIB) should be `libkvazaar.$(VER_MAJOR).dylib`, not just `libkvazaar.dylib`, assuming that $(VER_MAJOR) will correspond to the library version and not necessarily the overall kvazaar version. And the install-lib larget should of course should create the unversioned `libkvazaar.dylib` symlink.  The triple digit versioned library is no longer needed on Darwin.
* Also the linker command should include `-install_name $(LIBDIR)/$(DYLIB)` so that programs linking to the library will find it at runtime without using horrible hacks like DYLD_LIBRARY_PATH.
* And lastly, `-compatibility_version $(VER_MAJOR)` should also be in the linker command.

**Comment by Venti-** [comment]
@lu-zero I think that would be great.

**Comment by aryla** [comment]
@nieder thanks for the information! I changed the file name and added the options you suggested. Does is look correct now?

**Comment by nieder** [comment]
Just had time to finally check the new dylib code  The generated dylib does look to be correct now.

**Comment by gaming-hacker** [comment]
ii got the lib to compile on osx, with Xcode 7.1 but cannot get latest ffmpeg to recognize it.

**Comment by aryla** [comment]
@gaming-hacker, what is the error message in FFmpeg's config.log? Did you check that you are using compatible versions of FFmpeg and Kvazaar?

Please create a new issue if it still doesn't work.
